### ISSUE TITLE
buff.electricity not working?

### ISSUE THREAD

**Issue by badlydrawnben** [aallan/node-owlintuition#4]
Hi, 
Sorry I'm nowhere near clever enough at node.js things to fix this. When I fire up the monitoring I get this error:

```
 /home/pi/node_modules/owlintuition/owl.js:151
            buff.electricity.chan.forEach(function(entry) {
                             ^
TypeError: Cannot read property 'forEach' of undefined
    at Socket.<anonymous> (/home/pi/node_modules/owlintuition/owl.js:151:25)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

When I comment out all of the buff.electricity conditional IF statement code, then the rest of the script runs fine and it spits out the solar pv json data that I am after. Would still like to get the electricity generated data to work too though.

Thanks,
Ben

**Comment by aallan** [comment]
Possibly fixed in a recent pull request?

**Comment by BenWoodford** [comment]
Older units still seem to use `buff.electricity.chan` instead, so I've submitted a PR that handles this with backwards compatibility: https://github.com/aallan/node-owlintuition/pull/11
